server:
  port: 8080

spring:
  application:
    name: Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: bloglite-content-route
          uri: lb://BlogLite-Content
          predicates:
            - Path=/api/**
        - id: bloglite-auth-route
          uri: lb://BlogLite-Auth
          predicates:
            - Path=/apiAuth/**
bloglite:
  jwt:
    expireTime: 259200000 # 3 days
    secretKey: DoNotUseThisAsYourSecretKey