server:
  port: 52580

spring:
  application:
    name: BlogLite-Auth
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BlogLite-Auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

bloglite:
  jwt:
    expireTime: 259200000 # 3 days
    secretKey: DoNotUseThisAsYourSecretKey