server:
  port: 52480

logging:
  level:
    com.wsmrxd.bloglite.controller: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bloglite
    password: wsmrxd
    username: root
  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

myConfig:
  domain: whiskeyxd.top
  jwt:
    expireTime: 259200000 # 3 days
    secretKey: DoNotUseThisAsYourSecretKey
  image:
    repositoryPath: D://dev/nginx-1.25.1/html/image
    nginxContext: http://127.0.0.1/image/
    defaultCollectionImage: https://picx.zhimg.com/4b70deef7_l.jpg?source=d16d100b
    defaultBlogCardImage: https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg
  comment:
    coolDownMinutes: 1
    needReview: true
  blog:
    pvIncreaseCoolDownMinute: 1   # 同IP访问同一文章，此段时间内的重复访问仅统计一次
    searchEngine: SQL      # 此项值为RedisSearch或SQL，未定义的时候默认通过SQL搜索
  misc:
    nuxtDevPort: 3000