server:
  port: 52480

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bloglite
    password: wsmrxd
    username: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
